name: Create Release

on:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  TAG_PREFIX: v

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          tag: ${{ env.TAG_PREFIX }}${{ github.run_number }}
          commit: ${{ github.sha }}
          body: |
            - Ref: ${{ github.ref }}
            - Modified: ${{ github.event.head_commit.modified }}
            - Added: ${{ github.event.head_commit.added }}
            - Removed: ${{ github.event.head_commit.removed }}
            - Message: ${{ github.event.head_commit.message }}
            - Author: ${{ github.event.head_commit.author.name }}
            - Date: ${{ github.event.head_commit.timestamp }}
