name: Create Release

on:
  push:
    branches:
      - master

env:
  TAG_PREFIX: v

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latest-tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag::$latest_tag"

      - name: Create new tag
        run: |
          tag=$(echo ${{ steps.latest-tag.outputs.tag }} | awk -F. '{$NF+=20; OFS="."; print $0}')
          git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
          git config --global user.name "Your Name"
          git tag "$TAG_PREFIX$tag"
          git push origin "$TAG_PREFIX$tag"

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: "$TAG_PREFIX${{ steps.latest-tag.outputs.tag }}"
          release_name: Release "$TAG_PREFIX${{ steps.latest-tag.outputs.tag }}"
          draft: false
          prerelease: false
