name: Create Release

on:
  push:
    tags:
    - '*'
    branches:
      - main

env:
  TAG_PREFIX: v

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
